language: rust
cache: cargo
rust:
                  - nightly-2017-03-21
matrix:
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt
script:
- cargo fmt -- --write-mode=diff
- cargo build
- cargo test